// Copyright © 2008-2019 Pioneer Developers. See AUTHORS.txt for details
// Licensed under the terms of the GPL v3. See licenses/GPL-3.txt

#include "galaxy/Economy.h"

#include "Lang.h"

namespace GalacticEconomy {

	const CommodityInfo COMMODITY_DATA[COMMODITY_COUNT] = {
		{ Lang::COMMODITY_NONE,
			{},
			EconType::NONE },
		{ Lang::HYDROGEN,
			{},
			EconType::MINING },
		{ Lang::LIQUID_OXYGEN,
			{ Commodity::WATER, Commodity::INDUSTRIAL_MACHINERY },
			EconType::MINING },
		{ Lang::METAL_ORE,
			{ Commodity::MINING_MACHINERY },
			EconType::MINING },
		{ Lang::CARBON_ORE,
			{ Commodity::MINING_MACHINERY },
			EconType::MINING },
		{ Lang::METAL_ALLOYS,
			{ Commodity::METAL_ORE, Commodity::INDUSTRIAL_MACHINERY },
			EconType::INDUSTRY },
		{ Lang::PLASTICS,
			{ Commodity::CARBON_ORE, Commodity::INDUSTRIAL_MACHINERY },
			EconType::INDUSTRY },
		{ Lang::FRUIT_AND_VEG,
			{ Commodity::FARM_MACHINERY, Commodity::FERTILIZER },
			EconType::AGRICULTURE },
		{ Lang::ANIMAL_MEAT,
			{ Commodity::FARM_MACHINERY, Commodity::FERTILIZER },
			EconType::AGRICULTURE },
		{ Lang::LIVE_ANIMALS,
			{ Commodity::FARM_MACHINERY, Commodity::FERTILIZER },
			EconType::AGRICULTURE },
		{ Lang::LIQUOR,
			{ Commodity::FARM_MACHINERY, Commodity::FERTILIZER },
			EconType::AGRICULTURE },
		{ Lang::GRAIN,
			{ Commodity::FARM_MACHINERY, Commodity::FERTILIZER },
			EconType::AGRICULTURE },
		{ Lang::TEXTILES,
			{ Commodity::PLASTICS },
			EconType::INDUSTRY },
		{ Lang::FERTILIZER,
			{ Commodity::CARBON_ORE },
			EconType::INDUSTRY },
		{ Lang::WATER,
			{ Commodity::MINING_MACHINERY },
			EconType::MINING },
		{ Lang::MEDICINES,
			{ Commodity::COMPUTERS, Commodity::CARBON_ORE },
			EconType::INDUSTRY },
		{ Lang::CONSUMER_GOODS,
			{ Commodity::PLASTICS, Commodity::TEXTILES },
			EconType::INDUSTRY },
		{ Lang::COMPUTERS,
			{ Commodity::PRECIOUS_METALS, Commodity::INDUSTRIAL_MACHINERY },
			EconType::INDUSTRY },
		{ Lang::ROBOTS,
			{ Commodity::PLASTICS, Commodity::COMPUTERS },
			EconType::INDUSTRY },
		{ Lang::PRECIOUS_METALS,
			{ Commodity::MINING_MACHINERY },
			EconType::MINING },
		{ Lang::INDUSTRIAL_MACHINERY,
			{ Commodity::METAL_ALLOYS, Commodity::ROBOTS },
			EconType::INDUSTRY },
		{ Lang::FARM_MACHINERY,
			{ Commodity::METAL_ALLOYS, Commodity::ROBOTS },
			EconType::INDUSTRY },
		{ Lang::MINING_MACHINERY,
			{ Commodity::METAL_ALLOYS, Commodity::ROBOTS },
			EconType::INDUSTRY },
		{ Lang::AIR_PROCESSORS,
			{ Commodity::PLASTICS, Commodity::INDUSTRIAL_MACHINERY },
			EconType::INDUSTRY },
		{ Lang::SLAVES,
			{},
			EconType::AGRICULTURE },
		{ Lang::HAND_WEAPONS,
			{ Commodity::COMPUTERS },
			EconType::INDUSTRY },
		{ Lang::BATTLE_WEAPONS,
			{ Commodity::INDUSTRIAL_MACHINERY, Commodity::METAL_ALLOYS },
			EconType::INDUSTRY },
		{ Lang::NERVE_GAS,
			{},
			EconType::INDUSTRY },
		{ Lang::NARCOTICS,
			{},
			EconType::INDUSTRY },
		{ Lang::MILITARY_FUEL,
			{ Commodity::HYDROGEN },
			EconType::INDUSTRY },
		{ Lang::RUBBISH,
			{},
			EconType::INDUSTRY },
		{ Lang::RADIOACTIVES,
			{},
			EconType::INDUSTRY }
	};

} // namespace GalacticEconomy
