name: CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

jobs:

  cd_ubuntu_x86_64:
    runs-on: ubuntu-latest
    env:
      OUTPUT: endless-sky-x86_64-continuous.tar.gz
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev
      - name: Build Application
        run: |
          ./bootstrap
          cmake .
          make
